baseURL = 'https://www.aleainteractive.com/'
languageCode = 'en-us'
title = 'Alea Interactive'

[params]
favicon = "/favicon.ico"
logo = "/Logo_Webseite.svg"
description = "Alea Interactive is an indie-studio from Kempten, Germany. Discover their current project \"Fiets - Together\", a co-op cycling game for 2-4 player!"

# Social Links
[[params.social]]
  name = "steam"
  displayName = "Steam"
  url = "https://store.steampowered.com/app/4347770/FietsTogether/"
[[params.social]]
  name = "youtube"
  displayName = "YouTube"
  url = "https://www.youtube.com/@AleaInteractive"
[[params.social]]
  name = "instagram"
  displayName = "Instagram"
  url = "https://www.instagram.com/aleainteractive/"
[[params.social]]
  name = "tiktok"
  displayName = "TikTok"
  url = "https://www.tiktok.com/@aleainteractive"
[[params.social]]
  name = "twitter"
  displayName = "Twitter"
  url = "https://twitter.com/AleaInteractive"
[[params.social]]
  name = "linkedin"
  displayName = "LinkedIn"
  url = "https://de.linkedin.com/company/alea-interactive"
